
version: 1.0.{build}
image: Visual Studio 2017
shallow_clone: true

platform:
  - x86

configuration:
  - Debug
  - Release

cache:
  - C:\3rd_party

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))

  # Prepare for NMake
  - if "%platform%" == "x86" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%platform%" == "x64" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64

  # ffmpeg
  - ps: |
      $FFMPEG_VERSION = "4.0"
      $FFMPEGDIR = "C:\3rd_party\ffmpeg-$FFMPEG_VERSION"
      if (!(Test-Path -Path $FFMPEGDIR)) {
        Start-FileDownload https://ffmpeg.zeranoe.com/builds/win32/dev/ffmpeg-$FFMPEG_VERSION-win32-dev.zip
        7z x ffmpeg-$FFMPEG_VERSION-win32-dev.zip -aoa -oC:\3rd_party
        Rename-Item -Path C:\3rd_party\ffmpeg-$FFMPEG_VERSION-win32-dev -NewName $FFMPEGDIR
      }
      $env:FFMPEGDIR = $FFMPEGDIR

  # openal
  - ps: |
      $OPENAL_VERSION = "1.18.2"
      $OPENALDIR = "C:\3rd_party\openal-$OPENAL_VERSION"
      if (!(Test-Path -Path $OPENALDIR)) {
        Start-FileDownload http://kcat.strangesoft.net/openal-binaries/openal-soft-$OPENAL_VERSION-bin.zip
        7z x openal-soft-$OPENAL_VERSION-bin.zip -aoa -oC:\3rd_party
        Rename-Item -Path C:\3rd_party\openal-soft-$OPENAL_VERSION-bin -NewName $OPENALDIR
      }
      $env:OPENALDIR = $OPENALDIR

  # zlib
  - ps: |
      $ZLIB_VERSION = "1.2.11"
      $ZLIBDIR = "C:\3rd_party\zlib-$ZLIB_VERSION"
      if (!(Test-Path -Path $ZLIBDIR)) {
        $LINK_VER = $ZLIB_VERSION -Replace '[.]',''
        Start-FileDownload http://www.zlib.net/zlib$LINK_VER.zip
        7z x zlib$LINK_VER.zip -aoa -oC:\3rd_party
        cd $ZLIBDIR
        nmake /f win32\Makefile.msc
      }
      $env:ZLIBDIR = $ZLIBDIR

  # build debug
  - ps: |
      Get-ChildItem C:\3rd_party -rec

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%configuration%
  - cmd: nmake check_style
  - cmd: nmake
