version: 1.0.{build}

image: Visual Studio 2022

platform:
  - x86

configuration:
  - Debug
  - Release

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))

  # Start vc++ toolset
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git submodule update --init
  - cmd: cmake -G "NMake Makefiles" . -DCMAKE_BUILD_TYPE=%configuration%
  - cmd: nmake check_style
  - cmd: nmake
