name: Android Release Build

on:
  schedule:
     #schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  TAG_NAME: "nightly"
    
jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              arch: x86_64,
              os: ubuntu-22.04,
              extra-build-features: "",
            }
            
    steps:
    - name: Setup NDK
      run: |
        cd /usr/local/lib/android/sdk/ndk/
        wget --no-check-certificate 'https://onedrive.live.com/download?resid=3A7E32D08E399E75%212858&authkey=!AC_6V_xqURU9hlI' -O android-ndk-10421692-linux-x86_64.zip 
        unzip android-ndk-10421692-linux-x86_64.zip
        mv android-ndk-r27-canary 27.0.10421692
        echo "ANDROID_NDK=/usr/local/lib/android/sdk/ndk/27.0.10421692" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/27.0.10421692" >> $GITHUB_ENV
        echo "ANDROID_NDK_LATEST_HOME=/usr/local/lib/android/sdk/ndk/27.0.10421692" >> $GITHUB_ENV        
        echo "ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.0.10421692" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
          sudo apt-get install -y yasm
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-12-multilib g++-12-multilib
          sudo apt-get install -y libgcc-s1:i386 libstdc++6:i386 libatomic1:i386
          sudo apt-get install -y libavcodec58:i386 libavformat58:i386 libgomp1:i386
          sudo apt-get install -f libswresample3:i386
          sudo apt-get install -y libglu1-mesa-dev:i386 zlib1g-dev:i386
          sudo apt-get install -y libavformat-dev:i386 libavcodec-dev:i386 libswscale-dev:i386
          sudo apt-get install -y libopenal-dev:i386
          sudo apt-get install -y libsdl2-dev:i386

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17.0.6
        cache: gradle
        
    - name: Build ffmpeg
      working-directory: android/openenroth/jni/FFmpeg
      run: |
        ./build.sh

    - name: Build the app
      working-directory: android
      run: |
        ./gradlew -d assembleDebug
          
    - name: Publish unsigned apk package
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.TAG_NAME }}
        files: |
          android\openenroth\build\outputs\apk\debug\openenroth-debug.apk
        
