name: Android Release Build

on:
  schedule:
     #schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  TAG_NAME: "nightly"
    
jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              arch: x86_64,
              target: aarch64-linux-android,
              os: ubuntu-22.04,
              extra-build-features: "",
            }
            
    steps:
    - name: Setup NDK
      run: |
        cd /usr/local/lib/android/sdk/ndk/
        wget --no-check-certificate 'https://onedrive.live.com/download?resid=3A7E32D08E399E75%212858&authkey=!AC_6V_xqURU9hlI' -O android-ndk-10421692-linux-x86_64.zip 
        unzip android-ndk-10421692-linux-x86_64.zip
        echo "ANDROID_NDK=/usr/local/lib/android/sdk/ndk/android-ndk-r27-canary" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/android-ndk-r27-canary" >> $GITHUB_ENV
        echo "ANDROID_NDK_LATEST_HOME=/usr/local/lib/android/sdk/ndk/android-ndk-r27-canary" >> $GITHUB_ENV        
        echo "ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/android-ndk-r27-canary" >> $GITHUB_ENV
        
    - name: Check NDK
      run: |
        echo $ANDROID_NDK    
        echo $ANDROID_NDK_HOME    
        echo $ANDROID_NDK_LATEST_HOME    
        echo $ANDROID_NDK_ROOT  

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get install yasm

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
        
    - name: Build ffmpeg
      working-directory: android/openenroth/jni/FFmpeg
      run: |
        ./build.sh

    - name: Build the app
      working-directory: android
      run: |
        echo $ANDROID_NDK      
        ./gradlew assembleDebug
        ./gradlew assembleRelease
        
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: debug apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
          
    - name: Publish unsigned apk package
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.TAG_NAME }}
        files: |
          android/app/build/outputs/apk/debug/app-debug.apk
          android/app/build/outputs/apk/release/app-release.apk
        
        
        
