name: Build Release

on:
  schedule:
    - cron: 16 11 * * *
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
  push:
    tags:
      - '*'

env:
  TAG_NAME: nightly
  # These should be in sync, also this version is referenced in android/openenroth/build.gradle,
  # see https://developer.android.com/ndk/downloads.
  NDK_REVISION: r26-rc1
  NDK_VERSION: 26.0.10636728

jobs:
  advanceNightlyTag:
    name: Advance Nightly
    runs-on: ubuntu-latest
    outputs:
      tagName: ${{steps.outputReleaseTag.outputs.tagName }}
    steps:
      - name: Advance nightly tag
        uses: actions/github-script@v3
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          script: |
            try {
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: "tags/nightly"
                })
            } catch (e) {
              console.log("The nightly tag doesn't exist yet: " + e)
            }
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/nightly",
              sha: context.sha
            })

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: '${{ github.token }}'
          tag_name: nightly
          draft: true

      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          release_id: '${{ steps.latest_release.outputs.id }}'

      - name: Output Release Tag
        id: outputReleaseTag
        run: |
          echo "tagName=${{env.TAG_NAME}}" >> "$GITHUB_OUTPUT"


  build_android:
    name: Build Android Client
    needs: advanceNightlyTag
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        architecture:
          - x64
        target:
          - android
    steps:
      - name: Configure Fast APT Mirror
        uses: vegardit/fast-apt-mirror.sh@v1
        with: # the following parameters are listed with their action default values and are optional
          healthchecks:  10 # Number of mirrors from the mirrors list to check for availability and up-to-dateness
          speedtests:    6 # Maximum number of healthy mirrors to test for speed
          parallel:       2 # Number of parallel speed tests
          sample-size: 1024 # Number of kilobytes to download during the speed from each mirror
          sample-time:    3 # Maximum number of seconds within the sample download from a mirror must finish

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{ inputs.myCommit }}'

      - name: Decode Keystore
        if: '${{ env.super_secret != '''' }}'
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: android_keystore.jks
          fileDir: /home/runner/work/OpenEnroth/OpenEnroth/app/keystore/
          encodedString: '${{ secrets.KEYSTORE }}'
        env:
          super_secret: '${{ secrets.KEYSTORE }}'

      - name: Get NDK
        id: setup-ndk
        uses: captainurist/setup-ndk@main
        with:
          ndk-version: '${{env.NDK_REVISION}}'
          add-to-path: false
          local-cache: true

      - name: Setup NDK
        run: |
          ln -s "${{steps.setup-ndk.outputs.ndk-path}}" "/usr/local/lib/android/sdk/ndk/${{env.NDK_VERSION}}"

      - name: Install dependencies
        run: |
          sudo apt-get install -y yasm
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-13-multilib g++-13-multilib

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17.0.6
          cache: gradle

      - name: Check for ffmpeg cache
        id: ffmpeg-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            android/openenroth/jni/FFmpeg/android/
          key: ffmpeg-cache

      - name: Build ffmpeg
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        working-directory: android/openenroth/jni/FFmpeg
        run: |
          ./build.sh

      - name: Save ffmpeg cache
        if: steps.ffmpeg-cache.outputs.cache-hit != 'true'
        id: check-for-ffmpeg-save
        uses: actions/cache/save@v3
        with:
          path: |
            android/openenroth/jni/FFmpeg/android/
          key: ffmpeg-cache

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.10
        with:
          key: 'android-${{ matrix.configuration }}-multiarch'
          max-size: 250M

      - name: Build the app
        working-directory: android
        run: |
          ./gradlew "assemble${{ matrix.configuration }}" -Pandroid.native.buildOutput=verbose
        env:
          SIGNING_KEY_ALIAS: '${{ secrets.SIGNING_KEY_ALIAS }}'
          SIGNING_KEY_PASSWORD: '${{ secrets.SIGNING_KEY_PASSWORD }}'
          SIGNING_STORE_PASSWORD: '${{ secrets.SIGNING_STORE_PASSWORD }}'
          CMAKE_BUILD_PARALLEL_LEVEL: 3

      - name: Publish debug apk package
        if: '${{ matrix.configuration }} = "Debug"'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: '${{ env.TAG_NAME }}'
          files: |
            android/openenroth/build/outputs/apk/debug/openenroth-debug.apk

      - name: Publish release apk package
        if: '${{ matrix.configuration }} = "Release"'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: '${{ env.TAG_NAME }}'
          files: >
            android/openenroth/build/outputs/apk/release/openenroth-release-unsigned.apk

            android/openenroth/build/outputs/apk/release/openenroth-release-signed.apk

      - name: cleanup ccache
        run: >
          ccache -c

  build_linux:
    needs: advanceNightlyTag
    uses: ./.github/workflows/linux.yml
    secrets: inherit
    with:
      releaseTag: '${{needs.advanceNightlyTag.outputs.tagName}}'
      myCommit: '${{inputs.myCommit}}'

  build_macos:
    needs: advanceNightlyTag
    uses: ./.github/workflows/macos.yml
    secrets: inherit
    with:
      releaseTag: '${{needs.advanceNightlyTag.outputs.tagName}}'
      myCommit: '${{inputs.myCommit}}'

  build_windows:
    needs: advanceNightlyTag
    uses: ./.github/workflows/windows.yml
    secrets: inherit
    with:
      releaseTag: '${{needs.advanceNightlyTag.outputs.tagName}}'
      myCommit: '${{inputs.myCommit}}'
