name: MacOS Release Build

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  TAG_NAME: "nightly"

jobs:
  build_macos:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        architecture: [x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        brew uninstall --ignore-dependencies --force brotli giflib highway imath jpeg-turbo libpng xz lz4 zstd libtiff little-cms2 openexr webp jpeg-xl libvmaf aom dav1d freetype fontconfig frei0r ca-certificates gmp libunistring gettext libidn2 libtasn1 nettle p11-kit openssl@1.1 libevent libnghttp2 unbound gnutls lame fribidi pcre2 glib xorgproto libxau libxdmcp libxcb libx11 libxext libxrender lzo pixman cairo graphite2 icu4c harfbuzz libunibreak libass libbluray cjson mbedtls librist libsoxr libvidstab libogg libvorbis libvpx opencore-amr openjpeg opus rav1e libsamplerate flac mpg123 libsndfile rubberband snappy speex srt leptonica libb2 libarchive pango tesseract theora x264 x265 xvid libsodium zeromq zimg
        brew fetch --force --bottle-tag=arm64_big_sur sdl2
        brew install $(brew --cache --bottle-tag=arm64_big_sur sdl2)
        brew fetch --force --bottle-tag=arm64_big_sur ffmpeg@4 
        brew install $(brew --cache --bottle-tag=arm64_big_sur ffmpeg@4 )
        brew install cmake

    - name: Configure
      run: |
        cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DENABLE_TESTS=On -DCMAKE_PREFIX_PATH="/usr/local/opt/ffmpeg@4"

    - name: Build
      working-directory: build
      run: |
        make -j$(sysctl -n hw.logicalcpu)

    - name: Tests
      working-directory: build
      run: |
        make UnitTest
        
    - name: Prepare artifact
      run: |
        mkdir dist
        cp -r build/OpenEnroth.app dist/
        cp -r resources/* dist/
        hdiutil create OpenEnroth.dmg -ov -volname "OpenEnroth" -fs HFS+ -srcfolder dist
        
    - name: Zip Folder For Release
      if: success() || failure()
      run: zip -r ./MacOS_${{ env.TAG_NAME }}_${{ matrix.configuration }}_${{ matrix.architecture }}.zip dist

    - name: Publish Release
      if: success() || failure()	
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.TAG_NAME }}
        files: ${{ runner.os }}_${{ env.TAG_NAME }}_${{ matrix.configuration }}_${{ matrix.architecture }}.zip
        
