name: MacOS

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build_macos:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        architecture: [x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        brew install ffmpeg@4
        brew install sdl2

    - name: Configure
      run: |
        cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DENABLE_TESTS=On -DCMAKE_PREFIX_PATH="/usr/local/opt/ffmpeg@4"

    - name: Build
      working-directory: build
      run: |
        make -j$(sysctl -n hw.logicalcpu)

    - name: Tests
      working-directory: build
      run: |
        make UnitTest

    - name: Prepare artifact
      run: |
        mkdir dist
        cp -r build/Open_Enroth.app dist/
        cp -r resources/* dist/
        hdiutil create Open_Enroth.dmg -ov -volname "Open Enroth" -fs HFS+ -srcfolder dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Open Enroth (MacOS, ${{ matrix.configuration }}, ${{ matrix.architecture }})
        path: Open_Enroth.dmg
