name: Style

on:
  pull_request: null
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
  push: null
  release:
    types:
      - published

jobs:
  check_style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{ inputs.myCommit }}'

      - name: Install asdf
        uses: asdf-vm/actions/install@v3

      - name: Install LuaLS
        run: |
          asdf install lua-language-server latest
          lua-language-server --version

      - name: Configure
        run: |
          cmake -B build -DOE_USE_DUMMY_DEPENDENCIES=ON

      - name: Check style
        working-directory: build
        run: |
          make check_style
