name: Style

on:
  pull_request: null
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
  push: null
  release:
    types:
      - published

jobs:
  check_style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{ inputs.myCommit }}'
          
      - name: Install Homebrew and lua-language-server
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt-get update -y
          sudo apt-get install build-essential -y
          brew install lua-language-server

      - name: Configure
        run: |
          cmake -B build -DOE_USE_DUMMY_DEPENDENCIES=ON

      - name: Check style
        working-directory: build
        run: |
          make check_style
